version: '3'
services:
  traefik:
    image: traefik:2.4
    command: --api.insecure=true --providers.docker 
    depends_on:
      - nextcloud
    ports:
      - "80:80"
      - "8080:8080"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  mariadb:
    image: mariadb:10
    ports:
      - 3306:3306
    restart: always
    volumes:
      - /storage/nextcloud_compose/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  redis:
    image: redis:6
    restart: always
    volumes:
      - /storage/nextcloud_compose/redis:/data
  elasticsearch:
    image: schumischumi/elasticsearch-ingest-attachment:6.8.1-1
    ports:
      - "9200:9200"
  nextcloud:
    depends_on:
      - mariadb
      - redis
      - traefik
      - elasticsearch
    image: nextcloud:21
    labels:
      - "traefik.http.routers.nextcloud-http.rule=Host(`next.dockerhost.local`)"
    restart: always
    volumes:
      - /storage/nextcloud_compose/nextcloud/html:/var/www/html
